/* Generated by bin2c, do not edit manually */
#ifndef ___android256png_h_included
#define ___android256png_h_included

/* Contents of file .\chrome256.png */
extern const long int _android256png_size;
extern const unsigned char _android256png[6247];

#endif    /* ___android256png_h_included */
