/* Generated by bin2c, do not edit manually */
#ifndef ___android192png_h_included
#define ___android192png_h_included

/* Contents of file .\chrome192.png */
extern const long int _android192png_size;
extern const unsigned char _android192png[4503];

#endif    /* ___android192png_h_included */
