/* Generated by bin2c, do not edit manually */
#ifndef ___favicon_h_included
#define ___favicon_h_included

/* Contents of file .\favicon.ico */
extern const long int _favicon_size;
extern const unsigned char _favicon[15086];

#endif    /* ___favicon_h_included */
