/* Generated by bin2c, do not edit manually */
#ifndef ___favicon16_h_included
#define ___favicon16_h_included

/* Contents of file .\favicon16.png */
extern const long int _favicon16_size;
extern const unsigned char _favicon16[521];

#endif    /* ___favicon16_h_included */
