/* Generated by bin2c, do not edit manually */
#ifndef ___favicon32_h_included
#define ___favicon32_h_included

/* Contents of file .\favicon32.png */
extern const long int _favicon32_size;
extern const unsigned char _favicon32[901];

#endif    /* ___favicon32_h_included */
