/* Generated by bin2c, do not edit manually */
#ifndef ___iospng_h_included
#define ___iospng_h_included

/* Contents of file .\ios.png */
extern const long int _iospng_size;
extern const unsigned char _iospng[3639];

#endif    /* ___iospng_h_included */
