/* Generated by bin2c, do not edit manually */
#ifndef ___manifestjson_h_included
#define ___manifestjson_h_included

/* Contents of file .\manifest.json */
extern const long int _manifestjson_size;
extern const unsigned char _manifestjson[447];

#endif    /* ___manifestjson_h_included */
